# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19h5-jFisestn_xIRnVwLXdErz-PvR_4H
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain
# %pip install -U langgraph
# %pip install -U google-generativeai
# %pip install -U langchain-google-genai google-genai
# %pip install langchain-core
# %pip install langchain langchain-community

import os
import google.generativeai as genai
from google.colab import userdata

api_key = userdata.get("Gemini_API_Key")
os.environ["GOOGLE_API_KEY"] = api_key
genai.configure (api_key=api_key)

import langchain
import langchain_google_genai
from langchain_google_genai import ChatGoogleGenerativeAI

print("LangChain:", langchain.__version__)
print("LangChain Google GenAI:", langchain_google_genai.__version__)

# Usando 'models/gemma-4-26b-a4b-it' como un modelo disponible de la lista
llm = ChatGoogleGenerativeAI(model="gemma-4-26b-a4b-it")

print("Available models that support generateContent:")
for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(f"- {m.name}")

print("Available models that support generateContent:")
for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(f"- {m.name}")

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_core.prompts import PromptTemplate

from langchain_core.output_parsers import StrOutputParser
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_core.tools import tool
import os
from google.colab import userdata

# Ensure TAVILY_API_KEY is set if not already
if "TAVILY_API_KEY" not in os.environ:
    os.environ["TAVILY_API_KEY"] = userdata.get("tavily")

@tool
def busca_web(query: str) -> list:
  """Realiza una busqueda en la web el ranking de libros infantiles mas leídos"""

  tavily_search = TavilySearchResults(
      max_results=10,
      search_depth="advanced",
      max_tokens=1000 # Aumentado de 10 a 1000 para obtener contenido más completo
  )
  resultado_busca = tavily_search.invoke(query)
  return resultado_busca

tools = [busca_web]

# This line ensures llm_con_herramienta is bound to the updated llm.
llm_con_herramienta = llm.bind(tools=tools)

from langchain_core.messages import HumanMessage, AIMessage

def funcion_agente_web(state):
    messages = state['messages']
    last_message = messages[-1]

    # Decide whether to call a tool or generate a response
    response = llm_con_herramienta.invoke([last_message])

    # If the response contains tool_calls, return them
    if hasattr(response, 'tool_calls') and response.tool_calls:
        return {"messages": [response]}
    else:
        # Otherwise, assume it's a direct response from the LLM
        # In this specific case, we want to ensure a web_answer is returned if a tool was implicitly used
        # Given the previous context, we expect a web search to happen for the user query
        # Let's directly call the search tool if the LLM didn't explicitly call it yet.

        print("No tool call detected, performing web search...")
        search_results = busca_web.invoke({'query': last_message.content})
        web_answer = search_results[0]['content'] # Assuming the first result's content is what we want

        return {"messages": [AIMessage(content=web_answer)], "web_answer": web_answer}

llm_con_herramienta = llm.bind(tools=tools)

from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

from langgraph.graph import START, StateGraph, END

from typing import TypedDict, Annotated, List, Optional
import operator
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    chat_history: List[BaseMessage]
    messages: Annotated[List[BaseMessage], operator.add]
    web_answer: Optional[str]
    scientific_answer: Optional[str]
    final_answer: Optional[str]

workflow = StateGraph(AgentState)

from typing import TypedDict, Annotated, List, Optional
import operator
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langgraph.graph import START, StateGraph, END
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_core.tools import tool
import os
from google.colab import userdata

# Assuming llm and llm_con_herramienta are already defined from previous cells

# AgentState definition
class AgentState(TypedDict):
    chat_history: List[BaseMessage]
    messages: Annotated[List[BaseMessage], operator.add]
    web_answer: Optional[str]
    scientific_answer: Optional[str]
    final_answer: Optional[str]
    router_decision: Optional[str]

# Helper for web search (assuming tavily API key is set)
if "TAVILY_API_KEY" not in os.environ:
    os.environ["TAVILY_API_KEY"] = userdata.get("tavily")

@tool
def busca_web(query: str) -> list:
  """Realiza una busqueda en la web el ranking de libros infantiles mas leídos"""

  tavily_search = TavilySearchResults(
      max_results=10,
      search_depth="advanced",
      max_tokens=1000 # Aumentado de 10 a 1000 para obtener contenido más completo
  )
  resultado_busca = tavily_search.invoke(query)
  return resultado_busca

tools = [busca_web]
llm_con_herramienta = llm.bind(tools=tools)


# Agent functions
def router_agent(state: AgentState) -> dict:
    router_prompt = ChatPromptTemplate.from_template("""
Eres un agente ruteador. Tu tarea es decidir cuál agente es más apropiado
para responder la pregunta del usuario.

Pregunta del usuario: {user_query}

Puedes elegir entre las siguientes opciones:
- web_search: Usa esta opción si la pregunta requiere una búsqueda general en internet.
- scientific_search: Usa esta opción si la pregunta requiere artículos científicos.

Responde ÚNICAMENTE con el nombre de la opción (web_search o scientific_search).
""")

    router_chain = router_prompt | llm | StrOutputParser()

    decision = router_chain.invoke({"user_query": state["messages"][-1].content}).strip().lower()

    if decision == "web_search":
        return {"router_decision": "web_search"}
    elif decision == "scientific_search":
        return {"router_decision": "scientific_search"}
    else:
        print(f"Warning: LLM returned invalid decision: {decision}. Defaulting to web_search.")
        return {"router_decision": "web_search"}

def funcion_agente_web(state):
    messages = state['messages']
    last_message = messages[-1]

    response = llm_con_herramienta.invoke([last_message])

    if hasattr(response, 'tool_calls') and response.tool_calls:
        return {"messages": [response]}
    else:
        print("No tool call detected, performing web search...")
        search_results = busca_web.invoke({'query': last_message.content})
        web_answer = search_results[0]['content']
        return {"messages": [AIMessage(content=web_answer)], "web_answer": web_answer}

def funcion_agente_cientifico(state):
    print("DEBUG: scientific_search node executed.")
    # Placeholder for actual scientific search logic
    return {"scientific_answer": "No se realizó búsqueda científica (placeholder)."}

def supervisor_node(state: AgentState) -> AgentState:
    web_results = state.get("web_answer", "No se realizó búsqueda web.")
    scientific_results = state.get("scientific_answer", "No se realizó búsqueda científica.")
    messages = state.get("messages", [])
    chat_history = state.get("chat_history", [])

    final_answer_content = "## Resultados combinados de búsqueda\n\n"
    final_answer_content += "### Resultados desde la web\n\n" + web_results + "\n\n"
    final_answer_content += "### Artículos científicos\n\n" + scientific_results + "\n\n"

    output_state = AgentState(
        chat_history=chat_history,
        messages=messages,
        web_answer=web_results,
        scientific_answer=scientific_results,
        final_answer=final_answer_content
    )
    return output_state

# Workflow definition
workflow = StateGraph(AgentState)
workflow.add_node("router", router_agent)
workflow.add_node("web_search", funcion_agente_web)
workflow.add_node("scientific_search", funcion_agente_cientifico)
workflow.add_node("supervisor", supervisor_node)

workflow.add_edge(START, "router")
workflow.add_conditional_edges(
    "router",
    lambda state: state["router_decision"],
    {
        "web_search": "web_search",
        "scientific_search": "scientific_search"
    }
)
workflow.add_edge("web_search", "supervisor")
workflow.add_edge("scientific_search", "supervisor")
workflow.add_edge("supervisor", END)

app = workflow.compile()

from IPython.display import Image, display

Image(app.get_graph().draw_mermaid_png())

from langchain_core.messages import HumanMessage

resultado = app.invoke({"messages": [HumanMessage(content="Cuál es el impacto de la lectura en los niños")]})

print(resultado["web_answer"])

from langchain_community.tools.arxiv.tool import ArxivQueryRun

def supervisor_node(state: AgentState) -> AgentState:
  print(f"DEBUG: Supervisor Node - Incoming state: {state}") # Added debug print

  web_results = state.get("web_answer", "No se realizó búsqueda web.")
  scientific_results = state.get("scientific_answer", "No se realizó búsqueda científica.")
  messages = state.get("messages", [])
  chat_history = state.get("chat_history", []) # Ensure chat_history is also carried over

  final_answer_content = "## Resultados combinados de búsqueda\n\n"
  final_answer_content += "### Resultados desde la web\n\n" + web_results + "\n\n"
  final_answer_content += "### Artículos científicos\n\n" + scientific_results + "\n\n"

  # Construct and return a complete AgentState object, ensuring all fields are explicitly set
  output_state = AgentState(
      chat_history=chat_history,
      messages=messages,
      web_answer=web_results,
      scientific_answer=scientific_results,
      final_answer=final_answer_content
  )
  print(f"DEBUG: Supervisor Node - Outgoing AgentState: {output_state}") # Added debug print
  return output_state

def funcion_agente_cientifico(state):
    print("DEBUG: scientific_search node executed.") # Added debug print
    # This is a placeholder. Implement actual logic for the scientific agent here.
    return {"scientific_answer": "No se realizó búsqueda científica (placeholder)."}

# Initialize the workflow graph. Ensure this is done only once for the complete graph.
workflow = StateGraph(AgentState)

# Add nodes to the workflow
workflow.add_node("web_search", funcion_agente_web)
workflow.add_node("scientific_search", funcion_agente_cientifico)
workflow.add_node("supervisor", supervisor_node)

# Add edges to the workflow
workflow.add_edge(START, "web_search")
workflow.add_edge(START, "scientific_search")
workflow.add_edge("web_search", "supervisor")
workflow.add_edge("scientific_search", "supervisor")
workflow.add_edge("supervisor", END)

app = workflow.compile()

Image(app.get_graph().draw_mermaid_png())

from langchain_core.messages import HumanMessage

resultado = app.invoke({"messages": [HumanMessage(content="Cuál es el impacto de la lectura en los niños")]})
print(resultado["final_answer"])

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

def router_agent(state: AgentState) -> dict:

      router_prompt = ChatPromptTemplate.from_template("""
Eres un agente ruteador. Tu tarea es decidir cuál agente es más apropiado
para responder la pregunta del usuario.

Pregunta del usuario: {user_query}

Puedes elegir entre las siguientes opciones:
- web_search: Usa esta opción si la pregunta requiere una búsqueda general en internet.
- scientific_search: Usa esta opción si la pregunta requiere artículos científicos.

Responde ÚNICAMENTE con el nombre de la opción (web_search o scientific_search).
""")

      router_chain = router_prompt | llm | StrOutputParser()

      decision = router_chain.invoke({"user_query": state["messages"][-1].content}).strip().lower()

      if decision == "web_search":
        return {"router_decision": "web_search"}
      elif decision == "scientific_search":
        return {"router_decision": "scientific_search"}
      else:
        # Por defecto, si el LLM no responde con una opción válida
        print(f"Warning: LLM returned invalid decision: {decision}. Defaulting to web_search.")
        return {"router_decision": "web_search"}

workflow = StateGraph(AgentState)

workflow.add_node("router", router_agent)
workflow.add_node("web_search", funcion_agente_web)
workflow.add_node("scientific_search", funcion_agente_cientifico)
workflow.add_node("supervisor", supervisor_node)

workflow.add_edge(START, "router")

workflow.add_conditional_edges(
    "router",
    lambda state: state["router_decision"],
    {
        "web_search": "web_search",
        "scientific_search": "scientific_search"
    }
)

workflow.add_edge("web_search", "supervisor")
workflow.add_edge("scientific_search", "supervisor")
workflow.add_edge("supervisor", END)

app = workflow.compile()

Image(app.get_graph().draw_mermaid_png())

from langchain_core.messages import HumanMessage

resultado = app.invoke({
    "messages": [HumanMessage(content="Consejos prácticos para fomentar la lectura en los niños. Usa sólo fuentes web")]
})
print(resultado["final_answer"])

resultado = app.invoke({
    "messages": [HumanMessage(content="Consejos prácticos para fomentar la lectura en los niños. Usa sólo fuentes cientificas")]
})
print(resultado["final_answer"])

import gradio as gr

def run_graph(user_query):
  """Ejecuta el LangGraph con la pregunta del usuario y devuelve la respuesta final."""

  result = app.invoke({"messages": [HumanMessage(content=user_query)]})
  return result["final_answer"]

iface = gr.Interface(
    fn=run_graph,
    inputs=gr.Textbox(label="Pregunta lo que quieras:"),
    outputs=gr.Markdown(label="Respuesta Final"),
    title="Agente de Búsqueda Inteligente",
    description="Haz una pregunta y obtén una respuesta usando fuentes web o científicas."
)

iface.launch()